/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowseat;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sayeed
 */
public class WindowSeat extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * Creates new form WindowSeat
     */
    public WindowSeat() {
        initComponents();
        try{
            con = DB.connect();
            make_list();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        leavingFrom = new javax.swing.JLabel();
        start = new javax.swing.JComboBox();
        goingTo = new javax.swing.JLabel();
        end = new javax.swing.JComboBox();
        date = new javax.swing.JLabel();
        scarch = new javax.swing.JButton();
        close = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        calander = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        select = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book My Ticket");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        leavingFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leavingFrom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        leavingFrom.setText("Leaving From");

        start.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        goingTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        goingTo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        goingTo.setText("Going To");

        end.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        date.setText("Departure Date");

        scarch.setBackground(java.awt.Color.orange);
        scarch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scarch.setText("Search");
        scarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scarchActionPerformed(evt);
            }
        });

        close.setBackground(java.awt.Color.red);
        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        admin.setBackground(new java.awt.Color(0, 0, 51));
        admin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        calander.setDateFormatString("d, MMM yyyy");
        calander.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        select.setBackground(new java.awt.Color(102, 102, 255));
        select.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Time", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        result.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        result.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        result.setSelectionBackground(new java.awt.Color(0, 0, 102));
        result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(result);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Search Results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scarch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calander, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leavingFrom)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(goingTo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(leavingFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(goingTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calander, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(scarch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(close)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select)
                        .addGap(25, 25, 25))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets user's Start and Destination point
     * Shows option according to user's input in window
     * @param evt 
     */
    private void scarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scarchActionPerformed
        try{
            pst = con.prepareStatement("select * from rideinfo");
            rs = pst.executeQuery();

            String s = start.getSelectedItem().toString();
            String t = end.getSelectedItem().toString();
            boolean val = true;
            
            DefaultTableModel table = (DefaultTableModel) result.getModel();
            
            while(table.getRowCount()>0){
                for(int i=0;i<table.getRowCount(); i++){
                    table.removeRow(i);
                }
            }
            while(rs.next()){
                if(rs.getString("start").equalsIgnoreCase(s) && rs.getString("end").equalsIgnoreCase(t)){
                    table.addRow(new Object[]{rs.getString("id"),rs.getString("name").toUpperCase(),rs.getString("time"),rs.getString("price")});
                    val = false;
                }
            }
            if(val){
                JOptionPane.showMessageDialog(null,"No Result Found On The Search");
            }
            rs.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_scarchActionPerformed

    /**
     * Button to close the window
     * @param evt 
     */
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        try{
            int row = result.getSelectedRow();
            String str = result.getModel().getValueAt(row, 0).toString();
            Main.id = Integer.parseInt(str);
            if(Main.id != -1){
                viewSeat v = new viewSeat();
                v.setVisible(true);
                v.setResizable(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Select One Option");
        }
        
            
    }//GEN-LAST:event_selectActionPerformed

    private void resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultMouseClicked

    }//GEN-LAST:event_resultMouseClicked

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        admin a = new admin();
        a.setVisible(true);
        a.setResizable(false);
    }//GEN-LAST:event_adminActionPerformed

    /**
     * Set connection with database for latest update
     * Set's traveling option for user in combo box
     * @throws SQLException 
     */
    public void make_list() throws SQLException{
        pst = con.prepareStatement("select * from rideinfo");
        rs = pst.executeQuery();
        
        ArrayList<String> f = new ArrayList();
        ArrayList<String> t = new ArrayList();
        
        while(rs.next()){
            if(!f.contains(rs.getString("start")))
                f.add(rs.getString("start"));
                
            if(!t.contains(rs.getString("end")))
                t.add(rs.getString("end"));
        }
        
        rs.close();
        
        for(int i=0; i<Math.max(f.size(), t.size());i++){
            if(i<f.size())
                start.addItem(f.get(i).toUpperCase());
            if(i<t.size())
                end.addItem(t.get(i).toUpperCase());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowSeat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private com.toedter.calendar.JDateChooser calander;
    private javax.swing.JButton close;
    private javax.swing.JLabel date;
    private javax.swing.JComboBox end;
    private javax.swing.JLabel goingTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel leavingFrom;
    private javax.swing.JTable result;
    private javax.swing.JButton scarch;
    private javax.swing.JButton select;
    private javax.swing.JComboBox start;
    // End of variables declaration//GEN-END:variables
}